### ISSUE TITLE
Can't start new thread

### ISSUE THREAD

**Issue by kovarp15** [AlquistManager/alquist#30]
Alquist crashes with runtime error when being run locally. This happens as soon as I submit a first message via Alquist client.

Here is the log from command line:

* Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
172.17.0.1 - - [19/Nov/2016 15:04:51] "POST / HTTP/1.1" 200 -
[2016-11-19 15:05:38,263] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/alquist/IO/input.py", line 44, in get_input
    response = process_request(bot, state, context, text, session)
  File "/alquist/solver.py", line 37, in process_request
    dialogue_logger.log("Entering State: " + str(current_state), session)
  File "/alquist/dialogue_logger.py", line 17, in log
    log_thread.start()
  File "/usr/lib/python3.5/threading.py", line 844, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
172.17.0.1 - - [19/Nov/2016 15:05:38] "POST / HTTP/1.1" 500 -

**Comment by thePetrMarek** [comment]
I added handling of this exception. Does it work now?
